INSERT IGNORE INTO tag_category (id, name, slug, parent_id, sort_order) VALUES
  (1006, 'Color', 'color', 0, 6),
  (1007, 'Mood', 'mood', 0, 7);

INSERT IGNORE INTO tag (id, category_id, name, display_name_zh, description_zh, prompt_text, negative_prompt_text, preview_image_url, weight, usage_count) VALUES
  (2011, 1001, 'anime', '日系动画', '强调清晰角色设计、动画式上色和精致背景。', 'anime style, detailed painted background', NULL, '/images/tags/anime.webp', 1.10, 0),
  (2012, 1001, 'oil painting', '油画', '带有层叠笔触、厚涂高光和传统绘画质感。', 'traditional oil painting, visible brushwork', NULL, '/images/tags/oil-painting.webp', 1.05, 0),
  (2013, 1001, 'ink wash', '水墨', '使用墨色层次、留白和氤氲感表现东方画意。', 'Chinese ink wash painting, expressive brushwork', NULL, '/images/tags/ink-wash.webp', 1.10, 0),
  (2014, 1001, 'pixel art', '像素艺术', '使用明确像素块、有限色板和复古游戏画面语言。', 'polished pixel art, crisp pixel clusters', NULL, '/images/tags/pixel-art.webp', 1.00, 0),
  (2015, 1001, '3d render', '三维渲染', '强调立体造型、材质表现和三维空间光影。', 'premium 3D render, physically based materials', NULL, '/images/tags/3d-render.webp', 1.05, 0),
  (2016, 1001, 'fantasy art', '奇幻艺术', '适合魔法世界、架空建筑和富有想象力的场景。', 'fantasy art, enchanted world, magical atmosphere', NULL, '/images/tags/fantasy-art.webp', 1.10, 0),
  (2017, 1001, 'photorealistic', '写实摄影', '追求真实材质、自然光学和可信的摄影质感。', 'photorealistic, natural textures, realistic optics', 'cartoon, illustration, CGI', '/images/tags/photorealistic.webp', 1.20, 0),
  (2018, 1001, 'minimalist', '极简主义', '减少非必要元素，以简洁形状和留白突出主体。', 'minimalist composition, clean geometric forms', 'busy composition, clutter', '/images/tags/minimalist.webp', 1.00, 0),
  (2019, 1002, 'architecture', '建筑', '突出建筑结构、空间关系、尺度与设计细节。', 'detailed architecture, structural design', NULL, '/images/tags/architecture.webp', 1.10, 0),
  (2020, 1002, 'animal', '动物', '适合动物肖像、自然生态和人与动物互动场景。', 'detailed animal subject, natural anatomy', NULL, '/images/tags/animal.webp', 1.05, 0),
  (2021, 1002, 'product', '产品', '突出产品外观、材质、陈列方式和商业展示效果。', 'professional product photography, material detail', NULL, '/images/tags/product.webp', 1.10, 0),
  (2022, 1002, 'food', '美食', '强调食物质感、摆盘、色泽和令人食欲的氛围。', 'appetizing food photography, detailed plating', NULL, '/images/tags/food.webp', 1.05, 0),
  (2023, 1002, 'vehicle', '载具', '适合汽车、飞行器、船只和概念交通工具设计。', 'detailed vehicle design, believable engineering', NULL, '/images/tags/vehicle.webp', 1.05, 0),
  (2024, 1003, 'golden hour', '黄金时刻', '使用日出或日落前后的暖色低角度光线。', 'golden hour lighting, warm low-angle sunlight', NULL, '/images/tags/golden-hour.webp', 1.10, 0),
  (2025, 1003, 'neon light', '霓虹灯光', '使用青色、洋红等高饱和人工光营造都市感。', 'vivid neon lighting, cyan and magenta glow', NULL, '/images/tags/neon-light.webp', 1.05, 0),
  (2026, 1003, 'moonlight', '月光', '使用冷色银蓝光和柔和夜间阴影塑造静谧感。', 'cool silver moonlight, soft blue shadows', NULL, '/images/tags/moonlight.webp', 1.05, 0),
  (2027, 1003, 'volumetric light', '体积光', '表现穿过云雾或尘埃的清晰光束和空间层次。', 'volumetric lighting, visible light rays, atmospheric haze', NULL, '/images/tags/volumetric-light.webp', 1.15, 0),
  (2028, 1003, 'studio light', '棚拍光', '使用可控主光、补光和轮廓光塑造专业棚拍效果。', 'professional studio lighting, controlled key and fill light', NULL, '/images/tags/studio-light.webp', 1.10, 0),
  (2029, 1004, 'bird''s-eye view', '鸟瞰视角', '从高处向下观察主体，强调场景布局与空间关系。', 'bird''s-eye view, top-down aerial composition', NULL, '/images/tags/birds-eye-view.webp', 1.05, 0),
  (2030, 1004, 'low angle', '低机位', '从较低位置仰拍主体，增强高度、力量和戏剧性。', 'low-angle shot, upward perspective', NULL, '/images/tags/low-angle.webp', 1.05, 0),
  (2031, 1004, 'symmetrical composition', '对称构图', '以中轴和均衡关系建立稳定、庄重的画面秩序。', 'symmetrical composition, balanced central framing', NULL, '/images/tags/symmetrical-composition.webp', 1.00, 0),
  (2032, 1004, 'rule of thirds', '三分法', '将主体放在三分线或交点附近，让画面更自然平衡。', 'rule of thirds composition, balanced subject placement', NULL, '/images/tags/rule-of-thirds.webp', 1.00, 0),
  (2033, 1005, 'clean lines', '清晰线稿', '强调稳定轮廓、干净线条和易于识别的形状。', 'clean confident linework, crisp readable shapes', 'messy lines, rough sketch', '/images/tags/clean-lines.webp', 1.10, 0),
  (2034, 1005, 'professional color grading', '专业调色', '统一明暗、肤色与色彩关系，形成成熟的后期观感。', 'professional color grading, controlled contrast, cohesive colors', NULL, '/images/tags/professional-color-grading.webp', 1.10, 0),
  (2035, 1006, 'warm palette', '暖色调', '以琥珀、陶土、暖白和柔和红色营造亲近感。', 'warm color palette, amber and terracotta tones', NULL, '/images/tags/warm-palette.webp', 1.00, 0),
  (2036, 1006, 'cool palette', '冷色调', '以蓝、青、灰紫等冷色建立清爽或冷静的画面。', 'cool color palette, blue teal and slate tones', NULL, '/images/tags/cool-palette.webp', 1.00, 0),
  (2037, 1006, 'pastel colors', '粉彩色', '使用低饱和浅色，让画面显得柔和、轻盈和清新。', 'soft pastel colors, powder blue mint and lavender', NULL, '/images/tags/pastel-colors.webp', 1.00, 0),
  (2038, 1007, 'dreamy', '梦幻', '通过柔光、薄雾和超现实细节营造轻盈梦境感。', 'dreamy ethereal atmosphere, luminous mist', NULL, '/images/tags/dreamy.webp', 1.05, 0),
  (2039, 1007, 'mysterious', '神秘', '使用雾气、隐藏信息和克制光线制造未知与悬念。', 'mysterious atmosphere, fog, hidden silhouettes', NULL, '/images/tags/mysterious.webp', 1.05, 0),
  (2040, 1007, 'epic', '史诗感', '强调宏大尺度、戏剧天空和具有英雄感的场面。', 'epic atmosphere, monumental scale, dramatic sky', NULL, '/images/tags/epic.webp', 1.15, 0);
